### ISSUE TITLE
Option to ignore offline servers

### ISSUE THREAD

**Issue by leventdev** [laravel/pulse#315]
When deploying an app that uses Pulse on Kubernetes, every time there's a new deployment, the host name changes and shows as a new server.
This quickly clutters up the pulse site, and even after enough time passes to not have any server data from the selected period (1H, 6H, 24H, 7D), the server is still visible as offline.
It would be neat to have a configuration option for ignoring offline servers all together, or at least after there's no more data from them from the selected time period.
Example screenshot:
![image](https://github.com/laravel/pulse/assets/64219099/74446b69-13b7-452e-9b20-b8c871b72574)

**Comment by driesvints** [comment]
I think we'd appreciate a PR for this, thanks!

**Comment by DellanX** [comment]
Something to add to this, for future developers planning to add Pulse to their Kubernetes cluster, is to set the PULSE_SERVER_NAME to be the node name, which you can do by adding the following snippet to your container spec:
```yaml
          env:
            - name: PULSE_SERVER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
```

Furthermore, if you use a Daemon Set instead of a deployment, you can configure there to be exactly one pulse service per node.

This is my configuration:

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-pulse-check-default
  labels:
    tier: backend
    layer: pulse-check
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
      layer: pulse-check
  template:
    metadata:
      labels:
        tier: backend
        layer: pulse-check
    spec:
      imagePullSecrets:
        - name: {{ .Release.Name }}-registry-key
      containers:
        - name: pulse-check
          image: <docker-registry>:{{ .Values.version }}
          command:
            - php
          args:
            - artisan
            - pulse:check
          ports:
            - containerPort: 9000
          env:
            - name: PULSE_SERVER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}
            - secretRef:
                name: {{ .Release.Name }}

```

This will prevent a new server entry from being created each time you update your code 🙂

**Comment by razvan-p** [comment]
Do you have any docker / docker-compose solution?
The PULSE_SERVER_NAME from my docker-compose.yml seems to have string value "{{.Node.Hostname}}", not the host name.
```
services:
    app:
        environment:
            PULSE_SERVER_NAME: "{{.Node.Hostname}}"
```
